version: "3.7"
services:
  laravel:
    build:
      args:
        user: wwwxkz
        uid: 1000
      context: ./laravel
      dockerfile: Dockerfile
    image: lagfsd-laravel
    container_name: lagfsd-laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./laravel:/var/www
    networks:
      - lagfsd

  aspnet:
    container_name: lagfsd-aspnet
    image: "mcr.microsoft.com/dotnet/sdk:7.0"
    # depends_on: [ db ]
    # volumes:
    #   - ./:/app
    # command: dotnet watch --project ./app run --urls "http://0.0.0.0:80"    
    ports:
      - "8081:80"

  db:
    image: mysql:8.0
    container_name: lagfsd-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - lagfsd

  nginx:
    image: nginx:alpine
    container_name: lagfsd-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./laravel:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lagfsd

networks:
  lagfsd:
    driver: bridge
